# **SQL Data Cleaning, Transformation and Analysis: Raw Data of Open-Pit Copper Mine**

As there are no publicly available raw datasets for open-pit copper mine operations, synthetic data representing an open-pit copper mine was generated using generative artificial intelligence.

Generative artificial intelligence was used solely for the creation of the synthetic dataset. All SQL data extraction, cleaning, transformation, and analysis presented in this project are entirely my own work. 

The relational data model for the dataset is shown in the image below and consists of five tables, representing the following information:

1. **`01_energy_sources_raw`** – Energy sources used across the mine's operations <br><br>
   
2. **`02_operation_hierarchy_raw`** – The operations and sub-operations within the mine <br><br>
  
3. **`03_daily_production_raw`** – Daily mine production data <br><br>
   
4. **`04_daily_energy_consumption_raw`** – Daily energy consumption across the mine's operations <br><br>
  
5. **`05_monthly_energy_costs_raw`** – Monthly energy costs associated with the various energy sources used across different mine operations <br><br>
   
![Relational Database](Relational%20Database.png)

The raw datasets contained inconsistent text formatting, mixed date formats, non-numeric values, missing values, different energy units, and values outside expected ranges. SQL was used to clean and transform the datasets before combining them for the final energy, cost and emissions analysis.

## **Table 1 (01_energy_sources_raw) - Data Cleaning & Transformation:**

A new table, **`energy_sources_clean`**, was created from the **`01_energy_sources_raw`** table using the `CREATE TABLE` statement. 

During this process, several data cleaning and transformation steps were applied:

* The `TRIM()` function was used to remove leading and trailing spaces, while the `UPPER()` function was applied to standardise the formatting of energy source names <br><br>

* Energy units were standardised using a `CASE` statement to ensure consistency across the dataset. For example, values such as 'mwh' were converted to 'MWh', while 'litres' was standardised to 'L' <br><br>

* The **`emissions_factor_tco2e_per_unit`** column represents the emissions factor for each energy source, expressed as tonnes of CO₂e per unit of energy consumed. <br><br>As the original emissions factors were reported using different units depending on the energy source, i.e. MWh, GJ, and L, a new column named **`emissions_factor_tco2e_per_MJ`** was created in order to standardise the emissions factor values <br><br>

* A new column, **`MJ_per_unit`**, was also created to store the conversion factor between each energy source's original unit and megajoules (MJ).<br><br>  The conversion factors used were: <br><br> 1 MWh = 3,6000 MJ <br><br> 1L = 40 MJ (Diesel) <br><br> 1 GJ = 1000 MJ <br><br> This conversion factor was then used to calculate the standardised values in the **`emissions_factor_tco2e_per_MJ`** column. <br><br>

In [3]:
-- TABLE 1 - ENERGY SOURCES
CREATE TABLE energy_sources_clean AS 
SELECT * 
FROM '01_energy_sources_raw.csv';


UPDATE energy_sources_clean
	SET energy_source = UPPER(TRIM(energy_source)),
	
	standard_unit = CASE WHEN standard_unit ILIKE '%mwh%' THEN 'MWh'
	                     WHEN standard_unit ILIKE '%litres%' THEN 'L'
	                	 ELSE standard_unit END;

ALTER TABLE energy_sources_clean
	ADD COLUMN MJ_per_unit NUMERIC;

UPDATE energy_sources_clean
   SET MJ_per_unit = CASE WHEN standard_unit = 'MWh' THEN 3600
	                      WHEN standard_unit = 'L'   THEN 40
	                      WHEN standard_unit = 'GJ'  THEN 1000
	                      ELSE MJ_per_unit END;

ALTER TABLE energy_sources_clean
	ADD COLUMN emissions_factor_tco2e_per_MJ DOUBLE;

UPDATE energy_sources_clean
   SET emissions_factor_tco2e_per_MJ = emissions_factor_tco2e_per_unit/MJ_per_unit;

SELECT *
FROM energy_sources_clean;

   energy_source_id  ... emissions_factor_tco2e_per_MJ
0          16706266  ...                      0.000192
1          28450097  ...                      0.000067
2          53385195  ...                      0.000051
3          22757633  ...                      0.000008

[4 rows x 6 columns]

<br>## **Table 2 (02_operation_hierarchy_raw) - Data Cleaning & Transformation:**

A new table, **`operation_hierarchy_clean`**, was created from the **`02_operation_hierarchy_raw`** table using the `CREATE TABLE` statement.

The data cleaning and transformation steps applied were as follows:

* The `TRIM()` function was used to remove leading and trailing spaces for both the **`main_operation`** and **`sub_operation`** columns, while the `UPPER()` function was applied to standardise the formatting of main operation names <br><br>

In [6]:
-- TABLE 2 - OPERATION HIERARCHY
CREATE TABLE operation_hierarchy_clean AS 
SELECT * 
FROM '02_operation_hierarchy_raw.csv';

UPDATE operation_hierarchy_clean 
	SET main_operation = TRIM(UPPER(main_operation)),
	    sub_operation = TRIM(sub_operation);

SELECT *
FROM operation_hierarchy_clean;

    operation_id      main_operation  ... energy_criticality  typical_schedule
0       91340540    MINE DEVELOPMENT  ...             Medium              24/7
1       24914615    MINE DEVELOPMENT  ...               High              24/7
2       62814762    MINE DEVELOPMENT  ...             Medium         Day shift
3       77640743    MINE DEVELOPMENT  ...               High              24/7
4       83276760    MINE DEVELOPMENT  ...             Medium              24/7
5       61354486   MATERIAL MOVEMENT  ...               High              24/7
6       49569161   MATERIAL MOVEMENT  ...               High              24/7
7       98042943   MATERIAL MOVEMENT  ...               High              24/7
8       34819938   MATERIAL MOVEMENT  ...             Medium              24/7
9       98788663   MATERIAL MOVEMENT  ...               High              24/7
10      81519267  MINERAL PROCESSING  ...               High              24/7
11      60096075  MINERAL PROCESSING  ...               High              24/7
12      58956654  MINERAL PROCESSING  ...           Critical              24/7
13      28215636  MINERAL PROCESSING  ...           Critical              24/7
14      45769449  MINERAL PROCESSING  ...           Critical              24/7
15      47686418  MINERAL PROCESSING  ...               High              24/7
16      15289718  MINERAL PROCESSING  ...               High              24/7
17      21323883  MINERAL PROCESSING  ...               None              24/7
18      10655743  TAILINGS AND WATER  ...           Critical              24/7
19      73641141  TAILINGS AND WATER  ...               High              24/7
20      73642032  TAILINGS AND WATER  ...               High              24/7
21      36955136  TAILINGS AND WATER  ...               High              24/7
22      68659338  TAILINGS AND WATER  ...             Medium              24/7
23      40629202       SITE SERVICES  ...             Medium        Two shifts
24      85836525       SITE SERVICES  ...                Low              24/7
25      10469108       SITE SERVICES  ...             Medium              24/7
26      45614007       SITE SERVICES  ...             Medium        Two shifts

[27 rows x 7 columns]

<br>## **Table 3 (02_operation_hierarchy_raw) - Data Cleaning & Transformation:**

In [8]:
SELECT *
FROM daily_production_clean;

      production_record_id           production_date  ...  unit shift_reporting
0                 11535043 2025-01-01 00:00:00+00:00  ...     t     Daily total
1                 77562948 2025-01-01 00:00:00+00:00  ...     t     Daily total
2                 96003108 2025-01-01 00:00:00+00:00  ...     t     Daily total
3                 90389400 2025-01-01 00:00:00+00:00  ...     t     Daily total
4                 41973496 2025-01-01 00:00:00+00:00  ...     %     Daily total
...                    ...                       ...  ...   ...             ...
2311              28454822 2025-07-02 00:00:00+00:00  ...     %     Daily total
2312              32318115 2025-12-21 00:00:00+00:00  ...     t     Daily total
2313              67615010 2025-05-17 00:00:00+00:00  ...     %     Daily total
2314              74639440 2025-06-10 00:00:00+00:00  ...     %     Daily total
2315              40985916 2025-11-22 00:00:00+00:00  ...     t     Daily total

[2316 rows x 7 columns]